#!/usr/bin/env python3
"""
Merges existing individual EPG files into one combined 36-hour EPG.
Assumes the source files were already generated by other workflows.
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path

from lxml import etree

# List of existing EPG files to merge
SOURCES = [
    "output/epg.xml",           # From your main build.py
    "output/epg-ptn.xml",
    "output/epg-bestcoachtv.xml",
    # Add new generator files here when you create them
]

OUTPUT_FILE = Path("docs/epg-combined.xml")
MAX_HOURS = 36

def main():
    print("🔄 Starting daily combined EPG creation...")

    combined = etree.Element("tv")
    combined.set("generator-info-name", "ZipWave Combined EPG")
    combined.set("generator-info-url", "https://github.com/benevenstanciano/zip-epg")

    now = datetime.now()
    cutoff = now + timedelta(hours=MAX_HOURS)

    total_programmes = 0
    channels_seen = set()

    for source_path in SOURCES:
        path = Path(source_path)
        if not path.exists():
            print(f"⚠️  File not found (skipping): {path}")
            continue

        try:
            tree = etree.parse(str(path))
            root = tree.getroot()

            # Copy unique channel definitions
            for ch in root.findall("channel"):
                ch_id = ch.get("id")
                if ch_id and ch_id not in channels_seen:
                    combined.append(ch)
                    channels_seen.add(ch_id)

            # Copy only programmes in the next 36 hours
            for prog in root.findall("programme"):
                try:
                    start_str = prog.get("start")
                    if not start_str:
                        continue

                    # Parse start time (XMLTV format)
                    start = datetime.strptime(start_str[:14], "%Y%m%d%H%M%S")

                    if start > cutoff or start < now - timedelta(hours=4):  # small past buffer
                        continue

                    combined.append(prog)
                    total_programmes += 1
                except:
                    continue

        except Exception as e:
            print(f"❌ Error reading {path}: {e}")

    # Save the combined file
    OUTPUT_FILE.parent.mkdir(exist_ok=True)
    tree = etree.ElementTree(combined)
    tree.write(str(OUTPUT_FILE), encoding="utf-8", pretty_print=True, xml_declaration=True)

    print(f"✅ Combined EPG created successfully!")
    print(f"   • {total_programmes} programmes (next {MAX_HOURS} hours)")
    print(f"   • Channels: {len(channels_seen)}")
    print(f"   • Saved to: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
